env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  $: writable
  jQuery: writable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
